# Generated by Django 2.1.4 on 2019-01-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0004_auto_20190125_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='email',
            field=models.EmailField(default='oladipuporidwanolayinka@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consult',
            name='name',
            field=models.CharField(default='Ridwan Oladipupo', max_length=100),
            preserve_default=False,
        ),
    ]
