# Generated by Django 2.1.4 on 2019-01-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
