# Generated by Django 2.1.4 on 2019-01-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190118_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='subject',
        ),
    ]
