# Generated by Django 2.1.4 on 2019-01-21 13:59

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default="Vancouver's tower crane rental service and support leader since 1974", max_length=200)),
                ('screenshot', pyuploadcare.dj.models.ImageField(blank=True)),
            ],
        ),
    ]
