# Generated by Django 2.1.4 on 2019-01-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190121_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(default='My description goes here', max_length=200),
            preserve_default=False,
        ),
    ]
